awesome_coffice/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from coffee import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^', include('user.urls')),
    url(r'^', include('coffee.urls')),
    url(r'^captcha/', include('captcha.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

dangann/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('user.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^index_index/', views.index_index, name='index_index'),
    url(r'^', include('coffice.urls')),
    url(r'^', include('articles.urls')),
    url(r'^submit/', views.submit, name='submit'),
    url(r'^faq/', views.faq, name='faq'),
    url(r'^subscribe/', views.subscribe, name='subscribe'),
    url(r'^maintenance/', views.maintenance, name='maintenance'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = views.page_not_found
handler500 = views.server_error

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

user/urls.py
from django.conf.urls import url

from user import views

from rest_framework import routers

router = routers.DefaultRouter()

app_name = 'user'
urlpatterns = [
    url(r'^login/$', views.login_view, name='login'),
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^user/profile/$', views.profile_view, name='profile'),
    url(r'^user/profile/edit/$', views.profile_edit_view, name='profile_edit'),
    url(r'^user/profile/delete/$', views.profile_delete_view, name='profile_delete'),
    url(r'^user/password/edit/$', views.password_edit_view, name='password_edit'),
    url(r'^api/v1/users/$', views.users, name='users'),
    url(r'^api/v1/users/(?P<pk>[0-9]+)/$', views.user_detail, name='user_detail'),
    url(r'^api/v1/check_user/(?P<nickname>\w+)/$', views.check_user, name='check_user'),
    url(r'^api/v1/create_weixin_user/$', views.create_weixin_user, name='create_weixin_user'),
    url(r'^api/v1/update_weixin_user/(?P<pk>[0-9]+)/$', views.update_weixin_user, name='update_weixin_user'),
]

templates/partials/base.html
<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <title>
      {% block title %}
        dangann.com
      {% endblock %}
    </title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    {% load static %}
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/normalize.css" %}">
    <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static "css/helper.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    <link rel="stylesheet" href="{% static "css/blog.css" %}">
    <link rel="stylesheet" href="{% static "css/yue.css" %}">
    <link rel="stylesheet" href="{% static "css/zoom.min.css" %}">

    <script src="{% static "js/jquery-3.2.0.min.js" %}"></script>
    <script src="{% static "js/tether.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/nprogress.js" %}"></script>
    <script src="{% static "js/transition.min.js" %}"></script>
    <script src="{% static "js/zoom.min.js" %}"></script>

    {% block head %}
    {% endblock %}
  </head>

  <body>
    {% include "partials/navbar.html" %}

    {% block content %}
    {% endblock %}

    {% include "partials/footer.html" %}

    {% block pagejs %}
    {% endblock %}
  </body>
</html>

templates/partials/flash.html
{% if messages %}
  {% for message in messages %}
    <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
  {% endfor %}
{% endif %}

{% if form.errors %}
  <div class="alert alert-warning">
    {% for field in form %}
      {% if field.errors %}
        {% for error in field.errors %}
          {% if error != '认证码错误' and error != '这个字段是必须的' %}
            <li clas="#id_{{ field.name }}">{{ error|escape }}</li>
          {% elif error == '这个字段是必须的' %}
            <li clas="#id_{{ field.name }}">必须输入验证码！</li>
          {% else %}
            <li clas="#id_{{ field.name }}">验证码输入错误，请重新输入！</li>
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endfor %}
    {% if form.non_field_errors %}
      {{ form.non_field_errors }}
    {% endif %}
  </div>
{% endif %}


<!-- {% if form.captcha.errors %}
  <div class="alert alert-danger mt20" role="alert">
    验证码必须输入
  </div>
{% endif %} -->

templates/partials/footer.html
<footer class="blog-footer">
  <p>&copy; BreakWire Lab 2017. All Rights Reserved</p>
  <p>
    <a href="#" id="backtotop">Back to top</a>
  </p>
</footer>

<script>
  $('#backtotop').click(function() {
    $("html, body").animate({scrollTop: 0}, 1000);
  })
</script>

templates/partials/navbar.html
<nav class="navbar navbar-inverse bg-inverse navbar-toggleable-md">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand ml20" href="/">
    <span class="mr5"><i class="fa fa-coffee" aria-hidden="true" style=""></i></span> 单干 - 自由职业者社区
  </a>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li {% if title == 'articles' %} class="nav-item active" {% else %} class="nav-item" {% endif %}>
        <a href="/articles/" class="nav-link">文章</a>
      </li>
      <li {% if title == 'forum' %} class="nav-item active" {% else %} class="nav-item" {% endif %}>
        <a href="/forum/" class="nav-link">论坛</a>
      </li>
      <li {% if title == 'submit' %} class="nav-item active" {% else %} class="nav-item" {% endif %}>
        <a href="/submit/" class="nav-link">提交</a>
      </li>
      <li {% if title == 'faq' %} class="nav-item active" {% else %} class="nav-item" {% endif %}>
        <a href="/faq/" class="nav-link">FAQ</a>
      </li>
    </ul>


    <ul class="navbar-nav mr20">
      <a href="/subscribe/" class="btn btn-outline-info mr10"><span class="fa fa-envelope-o mr5"></span>SUBSCRIBE</a>
    </ul>

    <!-- {% if user.is_authenticated %}
      <ul class="navbar-nav">
        <a href="/subscribe/" class="btn btn-outline-info mr10"><span class="fa fa-envelope-o mr5"></span>SUBSCRIBE</a>
        <li {% if title == 'account' %} class="nav-item active dropdown" {% else %} class="nav-item dropdown" {% endif %}>
          <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img
                                    src="{{ user.avatar_thumbnail.url }}" alt=""
                                    style="width: 20px; height: 20px" class="mr5" hidden>{{user.email}}</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="{% url 'user:profile' %}">我的账户</a>
            <a class="dropdown-item" href="{% url 'user:logout' %}">退出</a>
          </div>
        </li>
      </ul>
    {% else %}
      <ul class="navbar-nav">
        <a href="/subscribe/" class="btn btn-outline-info mr10"><span class="fa fa-envelope-o mr5"></span>SUBSCRIBE</a>
        <a href="{% url 'user:login' %}" class="btn btn-outline-success mr10"><span class="fa fa-sign-in mr5"></span>登录</a>
        <a href="{% url 'user:signup' %}" class="btn btn-outline-success"><span class="fa fa-user-plus mr5"></span>注册</a>
      </ul>
    {% endif %} -->

  </div>
</nav>

templates/partials/working-on.html
<div class="container">
  <h1 class="centerh">Working On</h1>
  <p class="centerp">I am still Working on this......Please wait......</p>
</div>